/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import { motion } from "framer-motion-3d";

import * as THREE from "three";
import { animate, useMotionValue } from "framer-motion";
import { useFrame } from "@react-three/fiber";

export function Office(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF(
    "models/portfolio_scene_baked_final.gltf"
  );
  const texture = useTexture("textures/baked.jpg");
  const textureVSCode = useVideoTexture("textures/vscode.mp4");

  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  });

  const textureOpacity = useMotionValue(0);
  const glassTextureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0, {
      duration: 0.8,
    });
    animate(glassTextureOpacity, section === 0 ? 0.42 : 0, {
      duration: 0.8,
    });
  }, [section]);

  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
    textureGlassMaterial.opacity = glassTextureOpacity.get();
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Screen"
        geometry={nodes.Screen.geometry}
        position={[0.45, 0.94, -1.72]}
        rotation={[Math.PI, -1.099, Math.PI]}
      >
        <meshBasicMaterial map={textureVSCode} toneMapped={false} />
      </mesh>
      <group position={[-0.074, 0, -1.521]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Plane002_BlackWood001.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry}
          material={textureMaterial}
        />
      </group>
      <group position={[-0.868, 1.694, -2.038]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_ShelfSM_Shelf1_1.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry}
          material={textureMaterial}
        />
      </group>
      <motion.group
        scale={[0, 0, 0]}
        position={[-1.302, 2.071, -1.986]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh001"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh001_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh001_2"].geometry}
          material={textureMaterial}
        />
      </motion.group>
      <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        castShadow
        receiveShadow
        geometry={nodes.WawaRug.geometry}
        material={textureMaterial}
        position={[-0.281, 0.009, 0.765]}
      />
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        position={[-0.61, 2.044, -1.958]}
        rotation={[-Math.PI, 0.728, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh434900071.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh434900071_1.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh434900071_2.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh434900071_3.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh434900071_4.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh434900071_5.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <group
        name="keyboard"
        position={[0.215, 0.981, -1.215]}
        rotation={[0, -0.224, 0]}
        scale={0.63}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh425587018.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh425587018_1.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh425587018_2.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh425587018_3.geometry}
          material={textureMaterial}
        />
      </group>
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        position={[0.454, 0.939, -1.723]}
        rotation={[Math.PI, -1.099, Math.PI]}
        name="imac"
      >
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.iMac_1.geometry}
          material={textureMaterial}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iMac_1_1.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iMac_1_2.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <mesh
        name="mouse"
        castShadow
        receiveShadow
        geometry={nodes.Comp_Mouse.geometry}
        material={textureMaterial}
        position={[-0.008, 0, 0.076]}
      />
      <group position={[-0.78, 1.071, -1.61]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh24448074.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh24448074_1.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh24448074_2.geometry}
          material={textureMaterial}
        />
      </group>
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        position={[-2.019, -0.042, -1.526]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Houseplant_7_1.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Houseplant_7_2.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Houseplant_7_3.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        position={[2.13, -0.081, -1.055]}
        rotation={[-Math.PI, 0.672, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["palm_tree_01-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["palm_tree_01-Mesh_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["palm_tree_01-Mesh_2"].geometry}
          material={textureMaterial}
        />
      </motion.group>
      <group
        name="Chair"
        position={[0.089, 0, -0.664]}
        rotation={[0, -0.35, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Node-Mesh_1"].geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={textureMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_1.geometry}
        material={textureMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_2.geometry}
        material={textureMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_3.geometry}
        material={textureGlassMaterial}
      />
    </group>
  );

  // return (
  //   <group name="Scene" {...props} dispose={null}>
  //     <group position={[-0.074, 0, -1.521]} rotation={[0, -Math.PI / 2, 0]}>
  //       <mesh
  //         name="Plane001_Plane002_BlackWood001"
  //         geometry={nodes.Plane001_Plane002_BlackWood001.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Plane001_Plane002_BlackWood001_1"
  //         geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Plane001_Plane002_BlackWood001_2"
  //         geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Plane001_Plane002_BlackWood001_3"
  //         geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Plane001_Plane002_BlackWood001_4"
  //         geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry}
  //         material={textureMaterial}
  //       />
  //     </group>
  //     <group name="SM_ShelfSM_Shelf1" position={[-0.868, 1.694, -2.038]}>
  //       <mesh
  //         name="SM_ShelfSM_Shelf1_1"
  //         geometry={nodes.SM_ShelfSM_Shelf1_1.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="SM_ShelfSM_Shelf1_1_1"
  //         geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry}
  //         material={textureMaterial}
  //       />
  //     </group>
  //     <motion.group
  //       scale={[0, 0, 0]}
  //       animate={{
  //         scale: section === 0 ? 1 : 0,
  //       }}
  //       name="LavaLamp"
  //       position={[-1.302, 2.071, -1.986]}
  //     >
  //       <mesh
  //         name="Node-Mesh001"
  //         geometry={nodes["Node-Mesh001"].geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Node-Mesh001_1"
  //         geometry={nodes["Node-Mesh001_1"].geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Node-Mesh001_2"
  //         geometry={nodes["Node-Mesh001_2"].geometry}
  //         material={textureMaterial}
  //       />
  //     </motion.group>
  //     <motion.mesh
  //       scale={[0, 0, 0]}
  //       animate={{
  //         scale: section === 0 ? 1 : 0,
  //       }}
  //       name="WawaRug"
  //       geometry={nodes.WawaRug.geometry}
  //       material={textureMaterial}
  //       position={[-0.281, 0.009, 0.765]}
  //     />
  //     <group
  //       name="salameche"
  //       position={[-0.61, 2.044, -1.958]}
  //       rotation={[-Math.PI, 0.728, -Math.PI]}
  //     >
  //       <mesh
  //         name="mesh434900071"
  //         geometry={nodes.mesh434900071.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh434900071_1"
  //         geometry={nodes.mesh434900071_1.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh434900071_2"
  //         geometry={nodes.mesh434900071_2.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh434900071_3"
  //         geometry={nodes.mesh434900071_3.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh434900071_4"
  //         geometry={nodes.mesh434900071_4.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh434900071_5"
  //         geometry={nodes.mesh434900071_5.geometry}
  //         material={textureMaterial}
  //       />
  //     </group>
  //     <motion.group
  //       scale={[0, 0, 0]}
  //       animate={{
  //         scale: section === 0 ? 0.63 : 0,
  //       }}
  //       name="keyboard"
  //       position={[0.215, 0.981, -1.215]}
  //       rotation={[0, -0.224, 0]}
  //     >
  //       <mesh
  //         name="mesh425587018"
  //         geometry={nodes.mesh425587018.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh425587018_1"
  //         geometry={nodes.mesh425587018_1.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh425587018_2"
  //         geometry={nodes.mesh425587018_2.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh425587018_3"
  //         geometry={nodes.mesh425587018_3.geometry}
  //         material={textureMaterial}
  //       />
  //     </motion.group>
  //     <motion.group
  //       scale={[0, 0, 0]}
  //       animate={{
  //         scale: section === 0 ? 1 : 0,
  //       }}
  //       name="iMac"
  //       position={[0.454, 0.939, -1.723]}
  //       rotation={[Math.PI, -1.099, Math.PI]}
  //     >
  //       <mesh
  //         name="iMac_1"
  //         geometry={nodes.iMac_1.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="iMac_1_1"
  //         geometry={nodes.iMac_1_1.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="iMac_1_2"
  //         geometry={nodes.iMac_1_2.geometry}
  //         material={textureMaterial}
  //       />
  //     </motion.group>
  //     <mesh
  //       name="Comp_Mouse"
  //       geometry={nodes.Comp_Mouse.geometry}
  //       material={textureMaterial}
  //       position={[-0.008, 0, 0.076]}
  //     />
  //     <motion.group
  //       scale={[0, 0, 0]}
  //       animate={{
  //         scale: section === 0 ? 1 : 0,
  //       }}
  //       name="plant"
  //       position={[-0.78, 1.071, -1.61]}
  //     >
  //       <mesh
  //         name="mesh24448074"
  //         geometry={nodes.mesh24448074.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh24448074_1"
  //         geometry={nodes.mesh24448074_1.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="mesh24448074_2"
  //         geometry={nodes.mesh24448074_2.geometry}
  //         material={textureMaterial}
  //       />
  //     </motion.group>
  //     <motion.group
  //       scale={[0, 0, 0]}
  //       animate={{
  //         scale: section === 0 ? 1 : 0,
  //       }}
  //       name="Houseplant_7"
  //       position={[-2.019, -0.042, -1.526]}
  //       rotation={[-Math.PI / 2, 0, 0]}
  //     >
  //       <mesh
  //         name="Houseplant_7_1"
  //         geometry={nodes.Houseplant_7_1.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Houseplant_7_2"
  //         geometry={nodes.Houseplant_7_2.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Houseplant_7_3"
  //         geometry={nodes.Houseplant_7_3.geometry}
  //         material={textureMaterial}
  //       />
  //     </motion.group>
  //     <motion.group
  //       scale={[0, 0, 0]}
  //       animate={{
  //         scale: section === 0 ? 1 : 0,
  //       }}
  //       position={[2.13, -0.081, -1.055]}
  //       rotation={[-Math.PI, 0.672, -Math.PI]}
  //       name="palm_tree_01"
  //     >
  //       <mesh
  //         name="palm_tree_01-Mesh"
  //         geometry={nodes["palm_tree_01-Mesh"].geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="palm_tree_01-Mesh_1"
  //         geometry={nodes["palm_tree_01-Mesh_1"].geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="palm_tree_01-Mesh_2"
  //         geometry={nodes["palm_tree_01-Mesh_2"].geometry}
  //         material={textureMaterial}
  //       />
  //     </motion.group>
  //     <group
  //       name="Chair"
  //       position={[0.089, 0, -0.664]}
  //       rotation={[0, -0.35, 0]}
  //     >
  //       <mesh
  //         name="Node-Mesh"
  //         geometry={nodes["Node-Mesh"].geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Node-Mesh_1"
  //         geometry={nodes["Node-Mesh_1"].geometry}
  //         material={textureMaterial}
  //       />
  //     </group>
  //     <mesh
  //       name="Screen"
  //       geometry={nodes.Screen.geometry}
  //       material={textureMaterial}
  //       position={[0.454, 0.939, -1.723]}
  //       rotation={[Math.PI, -1.099, Math.PI]}
  //     />
  //     <group
  //       name="Plane"
  //       position={[-0.278, 0, -0.708]}
  //       rotation={[0, -0.376, 0]}
  //     >
  //       <mesh
  //         name="Plane001"
  //         geometry={nodes.Plane001.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Plane001_1"
  //         geometry={nodes.Plane001_1.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Plane001_2"
  //         geometry={nodes.Plane001_2.geometry}
  //         material={textureMaterial}
  //       />
  //       <mesh
  //         name="Plane001_3"
  //         geometry={nodes.Plane001_3.geometry}
  //         material={textureGlassMaterial}
  //       />
  //     </group>
  //   </group>
  // );
}

useGLTF.preload("models/portfolio_scene_baked_final.gltf");
useTexture.preload("textures/baked.jpg");
